package zone.clanker.opsx.task

import org.gradle.api.DefaultTask
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import zone.clanker.opsx.skill.SkillGenerator
import zone.clanker.opsx.skill.TaskInfo
import java.io.File
import java.nio.file.Files

/** Generates slash commands and instruction files for all agents. */
@DisableCachingByDefault(because = "Generates files in multiple agent-specific directories")
abstract class SyncTask : DefaultTask() {
    @get:Internal
    abstract val rootDir: Property<File>

    @get:Internal
    abstract val taskInfos: ListProperty<TaskInfo>

    @get:Internal
    abstract val includedBuildNames: ListProperty<String>

    @get:Internal
    abstract val includedBuildDirs: ListProperty<File>

    @get:Internal
    abstract val defaultAgent: Property<String>

    @TaskAction
    fun run() {
        val root = rootDir.get()
        val agent = defaultAgent.get()
        val generator =
            SkillGenerator(
                rootDir = root,
                tasks = taskInfos.get(),
                buildNames = includedBuildNames.get(),
                defaultAgent = agent,
            )
        val home = File(System.getProperty("user.home"))
        val sourceDir = File(home, SkillGenerator.SKILLS_DIR)

        // Clean source dir (we own everything here)
        if (sourceDir.exists()) {
            val mdFiles = sourceDir.listFiles().orEmpty()
            mdFiles.filter { it.name.endsWith(".md") }.forEach { it.delete() }
        }

        // Clean only symlinks pointing to our source dir from the active agent's dir
        val activeSkillDir =
            SkillGenerator.AGENT_CONFIG[agent]?.skillDir
                ?: error("Unknown agent '$agent'. Valid agents: ${SkillGenerator.AGENT_CONFIG.keys.joinToString()}")
        listOf(File(home, activeSkillDir), File(root, activeSkillDir)).forEach { dir ->
            if (dir.exists()) {
                val links = dir.listFiles().orEmpty()
                links.filter { isOpsxSymlink(it, sourceDir) }.forEach { it.delete() }
            }
        }

        generator.generate()

        // .clkx/skills/ is entirely ours — ignore everything
        writeGitignore(sourceDir, "*\n")

        // Agent target dirs may have user files — only ignore opsx-* skills
        listOf(File(home, activeSkillDir), File(root, activeSkillDir)).forEach { dir ->
            if (dir.exists()) {
                ensureOpsxIgnorePattern(dir)
            }
        }

        val fileCount = sourceDir.listFiles()?.count { it.name.endsWith(".md") } ?: 0
        logger.quiet("opsx-sync: $fileCount skills in ~/.clkx/skills/, symlinked to $agent")
    }

    private fun writeGitignore(
        dir: File,
        content: String,
    ) {
        val gitignore = File(dir, ".gitignore")
        gitignore.writeText("# Generated by opsx — do not edit\n$content")
    }

    private fun ensureOpsxIgnorePattern(dir: File) {
        val pattern = "opsx-*"
        val gitignore = File(dir, ".gitignore")
        if (gitignore.exists()) {
            val existing = gitignore.readText()
            if (existing.contains(pattern)) return
            gitignore.appendText("\n# Generated by opsx\n$pattern\n")
        } else {
            writeGitignore(dir, "$pattern\n")
        }
    }

    private fun isOpsxSymlink(
        file: File,
        sourceDir: File,
    ): Boolean {
        val path = file.toPath()
        if (!Files.isSymbolicLink(path)) return false
        return runCatching {
            val target = Files.readSymbolicLink(path)
            target.startsWith(sourceDir.toPath())
        }.getOrDefault(false)
    }
}
