package zone.clanker.opsx.task

import org.gradle.api.DefaultTask
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import zone.clanker.opsx.model.Agent
import zone.clanker.opsx.skill.SkillGenerator
import zone.clanker.opsx.skill.TaskInfo
import java.io.File
import java.nio.file.Files

/** Generates slash commands and instruction files for all agents. */
@DisableCachingByDefault(because = "Generates files in multiple agent-specific directories")
abstract class SyncTask : DefaultTask() {
    @get:Internal
    abstract val rootDir: Property<File>

    @get:Internal
    abstract val taskInfos: ListProperty<TaskInfo>

    @get:Internal
    abstract val includedBuildNames: ListProperty<String>

    @get:Internal
    abstract val includedBuildDirs: ListProperty<File>

    @get:Internal
    abstract val agents: ListProperty<String>

    @get:Internal
    abstract val skillDirectories: ListProperty<String>

    @get:Internal
    abstract val agentDirectories: ListProperty<String>

    @TaskAction
    fun run() {
        val root = rootDir.get()
        val agentIds = agents.get()
        if (agentIds.isEmpty()) {
            logger.warn("opsx-sync: no agents configured, skipping")
            return
        }
        val parsedAgents = agentIds.map { Agent.fromId(it) }
        val home = File(System.getProperty("user.home"))
        val sourceDir = File(home, SkillGenerator.SKILLS_DIR)

        cleanSourceDir(sourceDir)
        cleanAgentSymlinks(parsedAgents, home, root, sourceDir)

        buildGenerator(root, parsedAgents).generate()

        writeGitignore(sourceDir, "*\n")
        writeAgentIgnorePatterns(parsedAgents, home, root)

        val fileCount = sourceDir.listFiles()?.count { it.name.endsWith(".md") } ?: 0
        val agentSummary = parsedAgents.joinToString { it.id }
        logger.quiet("opsx-sync: $fileCount skills, agents: [$agentSummary]")
    }

    private fun buildGenerator(
        root: File,
        parsedAgents: List<Agent>,
    ): SkillGenerator {
        val resolvedSkillDirs = skillDirectories.get().map { File(root, it) }
        val resolvedAgentDirs = agentDirectories.get().map { File(root, it) }
        return SkillGenerator(
            rootDir = root,
            tasks = taskInfos.get(),
            buildNames = includedBuildNames.get(),
            agents = parsedAgents,
            additionalSourceDirs = resolvedSkillDirs,
            additionalAgentDirs = resolvedAgentDirs,
        )
    }

    private fun cleanSourceDir(sourceDir: File) {
        if (sourceDir.exists()) {
            val mdFiles = sourceDir.listFiles().orEmpty()
            mdFiles.filter { it.name.endsWith(".md") }.forEach { it.delete() }
        }
    }

    private fun cleanAgentSymlinks(
        parsedAgents: List<Agent>,
        home: File,
        root: File,
        sourceDir: File,
    ) {
        val dirs =
            parsedAgents.flatMap { agent ->
                listOf(File(home, agent.skillDir), File(root, agent.skillDir))
            }
        dirs.filter { it.exists() }.forEach { dir ->
            dir
                .listFiles()
                .orEmpty()
                .filter { isOpsxSymlink(it, sourceDir) }
                .forEach { it.delete() }
        }
    }

    private fun writeAgentIgnorePatterns(
        parsedAgents: List<Agent>,
        home: File,
        root: File,
    ) {
        parsedAgents.forEach { agent ->
            listOf(File(home, agent.skillDir), File(root, agent.skillDir)).forEach { dir ->
                if (dir.exists()) {
                    ensureOpsxIgnorePattern(dir)
                }
            }
        }
    }

    private fun writeGitignore(
        dir: File,
        content: String,
    ) {
        val gitignore = File(dir, ".gitignore")
        gitignore.writeText("# Generated by opsx — do not edit\n$content")
    }

    private fun ensureOpsxIgnorePattern(dir: File) {
        val pattern = "opsx-*"
        val gitignore = File(dir, ".gitignore")
        if (gitignore.exists()) {
            val existing = gitignore.readText()
            if (existing.contains(pattern)) return
            gitignore.appendText("\n# Generated by opsx\n$pattern\n")
        } else {
            writeGitignore(dir, "$pattern\n")
        }
    }

    private fun isOpsxSymlink(
        file: File,
        sourceDir: File,
    ): Boolean {
        val path = file.toPath()
        if (!Files.isSymbolicLink(path)) return false
        return runCatching {
            val target = Files.readSymbolicLink(path)
            target.startsWith(sourceDir.toPath())
        }.getOrDefault(false)
    }
}
